-- AlterTable
ALTER TABLE `Shift` ADD COLUMN `checkInAt` DATETIME(3) NULL,
    ADD COLUMN `checkOutAt` DATETIME(3) NULL,
    ADD COLUMN `notes` VARCHAR(191) NULL,
    ADD COLUMN `status` ENUM('SCHEDULED', 'COMPLETED', 'ABSENT') NOT NULL DEFAULT 'SCHEDULED';
